import React from 'react';
import style from '../../../styles/Testimonials.module.css';
import Testimonials_Blog_cards from './Testimonials_Blog_cards';
import img1 from '../../../assets/team/Pracas.png';
import img2 from '../../../assets/team/Prakash.webp';
import img3 from '../../../assets/team/Hiring.webp';
import img4 from '../../../assets/team/Sakchyam.webp';
import img5 from '../../../assets/team/Aashma.webp';
import img6 from '../../../assets/team/Bitisha.webp';
import img7 from '../../../assets/team/Lasta.webp';
import img8 from '../../../assets/team/Milan.webp';
import img9 from '../../../assets/team/Prakrit.webp';
import img10 from '../../../assets/team/Priyanka.webp';
import img11 from '../../../assets/team/Sagar.webp';
import img12 from '../../../assets/team/Rahul.webp';
import img13 from '../../../assets/team/Sarad.webp';

const testimonialsData = [
  { name: "Pracas", img: img1, title: "kathmandu", description:  "My stay at Sudarshan Agro Resort was an absolutely unforgettable experience. From the moment I arrived, I was welcomed by the breathtaking greenery, the soothing sounds of the flowing river, and the genuinely warm smiles of the resort staff. The eco-friendly cottages were exceptionally comfortable and charming, offering a perfect blend of modern amenities with natural, rustic aesthetics that made me feel completely at ease. Each day began with serene mornings by the river, followed by relaxing walks through the beautifully landscaped gardens and surrounding farms. The farm-to-table meals were freshly prepared and bursting with authentic local flavors, making every meal a delightful culinary journey. I particularly enjoyed the guided farm tours, nature trails, and interactive activities that allowed me to connect with the environment and learn about sustainable farming practices. The staff were attentive and always ready to assist, ensuring that every moment of my stay was worry-free and enjoyable. By the end of my visit, I felt completely rejuvenated, mentally refreshed, and deeply inspired. Sudarshan Agro Resort is not just a destination for relaxation; it is a sanctuary for the mind, body, and soul, offering a perfect balance of tranquility, adventure, and authentic cultural experiences." },
  { name: "Prakash", img: img2, title: "Pokhara, Nepal", description: "The resort exceeded all my expectations in every way imaginable. From the moment I arrived at Sudarshan Agro Resort, I was greeted with warmth and genuine hospitality that instantly made me feel at home. The staff were exceptional, anticipating every need and ensuring that every detail of my stay was perfect. Waking up to the serene river view each morning was a truly calming experience, and spending the evenings strolling through the beautifully landscaped gardens provided a peaceful escape from the stress of daily life. I particularly enjoyed the yoga sessions held at sunrise, which allowed me to start my day with mindfulness and energy, and the meditation corners scattered throughout the resort offered moments of quiet reflection and inner peace. The meals were thoughtfully prepared with fresh, locally sourced ingredients, bursting with authentic flavors that delighted every sense. Beyond relaxation, the resort offers a variety of activities, from guided farm tours to nature walks, perfectly balancing tranquility with adventure. Every aspect of the stay, from the eco-friendly accommodations to the attentive service, reflected care and attention to detail. Sudarshan Agro Resort is more than a getaway; it is a rejuvenating retreat for the mind, body, and soul, providing a memorable experience that I will cherish forever." },
  { name: "Rahul", img: img3, title: "Chitwan, Nepal", description: "Visiting Sudarshan Agro Resort was like stepping into an enchanting paradise where every detail is carefully curated to create a perfect experience. From the moment I arrived, I was captivated by the immaculate surroundings, featuring vibrant, lush flora, charming walking paths, and beautifully maintained gardens that invited exploration at every turn. The cottages were cozy, meticulously clean, and thoughtfully designed to combine comfort with a natural, rustic aesthetic, making me feel instantly at home. One of the highlights of my stay was the local cuisine, which was both authentic and absolutely delectable, prepared with fresh, high-quality ingredients that showcased the region’s flavors beautifully. I was particularly impressed by the friendliness and professionalism of the staff, who went above and beyond to ensure every need was met, offering personalized recommendations and anticipating every small detail to enhance my stay. Throughout my time at the resort, every moment felt calming and restorative, from leisurely strolls along the scenic pathways to quiet moments of reflection by the riverside. Sudarshan Agro Resort is truly a sanctuary for anyone seeking relaxation, rejuvenation, and a deep connection with nature, providing an unforgettable escape that nourishes both the body and the soul." },
  { name: "Sakchyam", img: img4, title: "Bhaktapur, Nepal", description:  "The eco-friendly design and sustainable practices at Sudarshan Agro Resort impressed me immensely. From the moment I arrived, I could see how nature is thoughtfully integrated into every aspect of the resort, creating a calming and harmonious environment. The cottages are designed to blend seamlessly with the surrounding greenery, offering comfort without compromising sustainability. The staff were professional, courteous, and always ready to assist, making every interaction a pleasant experience. I particularly enjoyed the scenic nature walks, where the vibrant flora and gentle river sounds provided a sense of peace and relaxation. The meals, prepared with fresh ingredients from local farms, were not only delicious but also offered a true taste of the region’s flavors. The activities at the resort, from exploring the gardens to learning about eco-friendly farming practices, were educational yet fun. Sudarshan Agro Resort balances comfort, nature, and thoughtful experiences beautifully, ensuring that every moment of the stay is memorable. I left feeling rejuvenated, inspired, and fully connected with the natural environment. I highly recommend this resort to anyone seeking a peaceful, restorative retreat where nature, sustainability, and hospitality come together perfectly." },
  { name: "Aashma", img: img5, title: "Lalitpur, Nepal", description:  "Sudarsan Agro Resort provided a wonderful escape from the hectic pace of daily life. From the moment I arrived, the lush green surroundings, fresh air, and the gentle sounds of the flowing river created a serene and tranquil atmosphere. The cottages were cozy, well-maintained, and thoughtfully designed to provide both comfort and a connection with nature. I particularly enjoyed the spa treatments, which were rejuvenating and helped me unwind completely. The cooking classes featuring local cuisine were not only fun but also educational, giving me insight into authentic flavors and traditional cooking techniques. Every meal at the resort was freshly prepared, flavorful, and a delight for the senses. The staff were attentive, friendly, and always ready to assist, ensuring a seamless and enjoyable stay. I also loved taking leisurely walks through the scenic gardens and surrounding farmland, where I could fully immerse myself in the calm and peaceful environment. Sudarshan Agro Resort offers the perfect balance of relaxation, adventure, and cultural experiences. By the end of my stay, I felt refreshed, inspired, and completely rejuvenated. I would highly recommend it to anyone looking for a serene and revitalizing retreat away from the city." },
  { name: "Bitisha", img: img6, title: "Biratnagar, Nepal", description: "The resort is a perfect blend of comfort and nature, providing an extraordinary experience for anyone looking to reconnect with the natural world. Each morning, I was greeted by the warm sunlight streaming over the river, creating a sense of peace and serenity. The cottages were beautifully designed, clean, and comfortable, offering a perfect place to relax after a day of exploration. The food at Sudarshan Agro Resort was exceptional, prepared with fresh ingredients and infused with traditional flavors that delighted every palate. The staff were attentive, friendly, and genuinely welcoming, ensuring that every aspect of my stay was seamless and enjoyable. I spent my days exploring the surrounding nature trails, walking along the riverside, and discovering the beautifully landscaped gardens. The resort provides a wonderful balance between relaxation and adventure, offering activities that are both engaging and soothing. From the serene environment to the thoughtfully planned experiences, every detail reflects care and attention. By the end of my visit, I felt fully rejuvenated and inspired, with a renewed sense of calm and connection to nature. Sudarshan Agro Resort is truly a haven for those seeking both comfort and tranquility in a natural setting." },
  { name: "Lasta", img: img7, title: "Butwal, Nepal", description: "Visiting Sudarshan Agro Resort was like entering a serene and enchanting world, where every detail is thoughtfully designed to create a peaceful and rejuvenating experience. From the moment I arrived, I was greeted by lush greenery, the gentle flow of the river, and an atmosphere that immediately made me feel calm and relaxed. The cottages were charming, comfortable, and eco-friendly, perfectly blending modern amenities with the natural surroundings. Every staff member I encountered was courteous, attentive, and genuinely caring, ensuring that my stay was seamless and enjoyable. I particularly loved the fresh and flavorful local cuisine, prepared with high-quality, locally sourced ingredients, which made every meal a delight. The resort offers a variety of activities that strike the perfect balance between adventure and relaxation, from scenic nature walks to cultural programs that showcase the traditions of the region. Spending my days exploring the gardens, walking along the riverside, and enjoying quiet moments in meditation corners left me feeling refreshed, inspired, and rejuvenated. Sudarshan Agro Resort is truly a sanctuary for the mind, body, and soul, offering an unforgettable experience for families, couples, and solo travelers alike. I can’t wait to return for another peaceful retreat." },
  { name: "Milan", img: img8, title: "Hetauda, Nepal", description:  "My stay at Sudarshan Agro Resort was incredibly rejuvenating and unforgettable. From the moment I arrived, I was surrounded by lush greenery, fresh air, and the soothing sounds of the river, creating an atmosphere of peace and tranquility. The staff’s hospitality was impeccable, always attentive and ensuring that every detail of my stay was perfect. I spent my days exploring the farm, walking along scenic river paths, and enjoying the serene gardens, which offered quiet spots for relaxation and reflection. The cottages were comfortable, clean, and thoughtfully designed to harmonize with the natural surroundings. I also enjoyed tasting the local delicacies, which were prepared with fresh ingredients and authentic flavors, making every meal a delightful experience. The resort combines a sense of adventure with moments of calm, from nature trails and guided tours to quiet meditation spots. Every interaction, every meal, and every activity contributed to a feeling of rejuvenation and inspiration. By the end of my stay, I felt refreshed, energized, and deeply connected to the peaceful environment. Sudarshan Agro Resort is a perfect destination for anyone seeking a restorative retreat, combining nature, comfort, and attentive service in a truly memorable way." },
  { name: "Prakrit", img: img9, title: "Dharan, Nepal", description:  "From the moment I arrived at Sudarshan Agro Resort, I felt an immediate sense of peace and relaxation. The eco-friendly cottages were beautifully designed, combining modern comforts with a natural aesthetic that blended perfectly with the surrounding greenery. Every corner of the resort was thoughtfully maintained, from the lush gardens to the gently flowing river that added a calming soundtrack to the stay. The staff were friendly, attentive, and always ready to assist, making every experience seamless and enjoyable. I particularly loved participating in the local cultural programs, which provided a fascinating insight into the traditions and customs of the region. The farm-to-table meals were fresh, flavorful, and authentically prepared, making each dining experience a delight. Mornings spent walking along the riverside and exploring the scenic pathways were incredibly refreshing, and I enjoyed discovering little spots to pause and appreciate nature. Sudarshan Agro Resort manages to offer both relaxation and authentic cultural experiences, creating an ideal escape from the stresses of daily life. By the end of my stay, I felt rejuvenated, inspired, and deeply connected to the peaceful surroundings. It is the perfect destination for anyone seeking tranquility, comfort, and a meaningful retreat in harmony with nature." },
  { name: "Priyanka", img: img10, title: "Janakpur, Nepal", description: "The hospitality at Sudarshan Agro Resort is absolutely unmatched. From the moment I arrived, I was welcomed by a serene and picturesque environment, where the lush greenery and flowing river created a perfect setting for relaxation. The staff were consistently friendly, professional, and attentive, ensuring that every need was met and every detail of my stay was flawless. The cottages were cozy, clean, and designed with a harmonious balance of comfort and natural aesthetics. I thoroughly enjoyed my mornings walking along the riverside and afternoons exploring the gardens, which offered peaceful spots for reflection and leisure. The local cuisine was delightful, with fresh ingredients and authentic flavors that made every meal an enjoyable experience. The resort provides a perfect combination of tranquility, nature, and comfort, offering opportunities to unwind, reconnect, and rejuvenate. Every aspect, from the environment to the services and amenities, contributes to a seamless and memorable stay. By the end of my visit, I felt refreshed, energized, and inspired. Sudarshan Agro Resort is an ideal destination for anyone looking for a serene retreat that nurtures the mind, body, and soul, making it a truly unforgettable experience." },
  { name: "Sagar", img: img11, title: "Nepalgunj, Nepal", description:  "Sudarshan Agro Resort is a hidden gem that provides an extraordinary experience for anyone seeking tranquility and connection with nature. From the moment I arrived, I was impressed by the dedication to sustainability, the well-maintained surroundings, and the harmony between modern comfort and natural beauty. The accommodations were comfortable, clean, and thoughtfully designed to maximize relaxation while offering stunning views of the greenery and river. The staff were attentive, friendly, and always willing to assist, making me feel welcome and valued throughout my stay. I enjoyed exploring the resort’s scenic gardens, walking along peaceful river paths, and participating in activities that connected me with the environment. The meals were fresh, authentic, and delicious, showcasing the flavors of the region in every dish. Every day at Sudarshan Agro Resort offered a perfect blend of relaxation, adventure, and cultural experiences, creating a truly memorable escape from the stresses of city life. By the end of my visit, I felt rejuvenated, inspired, and fully refreshed. The resort is ideal for families, couples, and solo travelers seeking a serene and immersive retreat that nourishes both the body and the soul, providing an unforgettable and transformative experience" },
  { name: "Rahul", img: img12, title: "Birtamod, Nepal", description:  "Sudarshan Agro Resort exceeded all of my expectations and provided a truly remarkable experience. From the moment I arrived, the serene environment and thoughtfully designed accommodations made me feel at home. The cottages were cozy, clean, and harmonized beautifully with the lush greenery surrounding the property. I particularly enjoyed the resort’s sustainable and eco-friendly practices, which added meaning to every aspect of my stay. Each day was filled with delightful experiences, from walking through the scenic gardens to enjoying freshly prepared meals bursting with authentic flavors. The evening bonfires and live music sessions created a warm, inviting atmosphere, perfect for relaxation and socializing. The staff were exceptionally friendly and attentive, ensuring that every need was met and every moment of my stay was enjoyable. Beyond comfort and hospitality, the resort offers a connection with nature that is both restorative and inspiring. I left feeling refreshed, rejuvenated, and full of positive energy. Sudarshan Agro Resort is truly a place where nature and comfort coexist beautifully, offering a perfect retreat for anyone seeking a peaceful, memorable, and enriching experience away from the bustle of city life." },
  { name: "Sarad", img: img13, title: "Dhangadhi, Nepal", description: "TSudarshan Agro Resort is truly a perfect destination for relaxation and reconnecting with nature. From the moment I arrived, I was greeted by lush greenery, serene river views, and a peaceful ambiance that immediately set the tone for a restorative stay. The cottages were charming, comfortable, and thoughtfully designed to blend seamlessly with the natural surroundings, providing both modern comforts and a sense of tranquility. The staff were incredibly welcoming, friendly, and attentive, ensuring that every detail of my stay was taken care of and that every moment felt special. I particularly enjoyed the fresh and delicious meals, prepared with locally sourced ingredients and authentic flavors that made every dining experience memorable. My days were spent exploring scenic walking paths, riverside trails, and the beautifully maintained gardens, offering the perfect opportunities to unwind and reflect. The resort’s dedication to eco-friendly practices and sustainability added to the charm, allowing me to appreciate the harmony between comfort and nature. By the end of my stay, I felt completely refreshed, inspired, and rejuvenated. Sudarshan Agro Resort is a sanctuary for anyone seeking peace, comfort, and a meaningful connection with the natural world, leaving memories that will last a lifetime." },
];

const Testimonials = () => {
  return (
    <div className={style.container}>
      <h3>Testimonials</h3>
      <div className={style.horizontal_line}></div>

      <div className={style.cards_row}>
        {testimonialsData.map((item, index) => (
          <Testimonials_Blog_cards
            key={index}
            img={item.img}
            name={item.name}
            title={item.title}
            description={item.description}
          />
        ))}
      </div>
    </div>
  );
};

export default Testimonials;
